# recommended markup settings if you use Markdown as your input format;
# other formats may require different settings

[highlight]
  # line numbers in a table layout will shift if code is wrapping, so better
  # not use it; visually both layouts have the same look and behavior
  lineNumbersInTable = false

  # the shipped variants come with their own modified chroma syntax highlighting
  # stylesheets which are linked in your generated HTML pages; you can use Hugo to generate
  # own stylesheets to your liking and use them in your variant;
  # if you want to use Hugo's internal styles instead of the shipped stylesheets:
  # - remove `noClasses` or set `noClasses = true`
  # - set `style` to a predefined style name
  # note: with using the internal styles, the `--CODE-theme` setting in your variant
  # stylesheet will be ignored and the internal style is used for all variants and
  # even print
  noClasses = false
  # style = 'tango'

[goldmark]
  [goldmark.extensions]
    strikethrough = false
    [goldmark.extensions.extras]
      [goldmark.extensions.extras.delete]
        enable = true
      [goldmark.extensions.extras.insert]
        enable = true
      [goldmark.extensions.extras.mark]
        enable = true
      [goldmark.extensions.extras.subscript]
        enable = true
      [goldmark.extensions.extras.superscript]
        enable = true

    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        # the settings chosen here match the default initialization
        # of the MathJax library chosen by the theme;
        # if you want to adjust to different values you also need
        # to set them in `[params] mathJaxInitialize`
        inline = [['\(', '\)'], ['$',  '$']]
        block  = [['\[', '\]'], ['$$', '$$']]
