name: Build website using Hugo version 0.143.1 (reflect production)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'

jobs:
  build:
    #runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        uses: actions/checkout@v4
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.143.1'
          extended: true
      
      - name: Build hugo site
        run: hugo --minify