name: Build website using the latest hugo version
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone this repo
        uses: actions/checkout@v3
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Build hugo site
        run: hugo --minify