name: Perform markdown linting

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'content/**/*.md'
      - 'README.md'
      - '.markdownlint.yml'
      - '.github/workflows/linting.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'content/**/*.md'
      - 'README.md'
      - '.markdownlint.yml'
      - '.github/workflows/linting.yml'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone this repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint content Markdown
        uses: rvben/rumdl@4997ff07b63c7a54d6a495ebcd3ce7f23ee1173f # v0.2.55
        with:
          version: '0.2.58'
          path: 'content/'
          config: '.markdownlint.yml'
          report-type: annotations

      - name: Lint README
        uses: rvben/rumdl@4997ff07b63c7a54d6a495ebcd3ce7f23ee1173f # v0.2.55
        with:
          version: '0.2.58'
          path: 'README.md'
          config: '.markdownlint.yml'
          report-type: annotations
